### PR TITLE
isMobileDevice

### PR DESCRIPTION
**Pull request by jico**

### CODE REVIEW

**Comment by cpcarey** [comment]
why `481px` and `1025px` as the default max width breakpoints instead of `480px` and `1024px`?

**Comment by cpcarey** [comment]
lgtm :wolf:

**Comment by tjhosford** [comment]
matchMedia is apparently only supported in IE10.  Do you have a shim you can use?  Otherwise you can implement isMobile based on user agent detection

**Comment by jico** [comment]
@TomHoss the way it's written though, it'll always return false if `matchMedia` doesn't exist, so it essentially won't consider IE users a mobile device ever, which isn't a problem (especially since we're not considering windows mobile, let alone whatever browser it uses). I'd like to avoid parsing User Agents since they can change, but I'll probably put in an option for that down the line.

**Comment by tjhosford** [comment]
@jico I see, sounds good.  The only downside is that it will return a false negative for mobile browsers which don't support the method such as Opera Mini and older versions of iOS/Android.  I guess we don't really need to support those anyway.

**Comment by tjhosford** [comment]
LGTM

**Pull request closed without merging**
